### Setup

In [ ]:
#!pip install opencv-contrib-python

In [ ]:
import numpy as np
import pandas as pd
import cv2
import matplotlib.pyplot as plt
%matplotlib inline  
# if you are running this code in Jupyter notebook

In [ ]:
import janitor

In [ ]:
import os
import glob
import math
from collections import Counter
from multiprocessing import Process
from time import sleep
from random import random
import warnings
warnings.filterwarnings('ignore')


In [ ]:
image_path = "C:/Users/shiho/Aij/SA_Instagram/opencv/image_file/"

In [ ]:
glob.glob("C:/Users/shiho/Aij/SA_Instagram/opencv/image_file/*")

['C:/Users/shiho/Aij/SA_Instagram/opencv/image_file\\279693449_1091281408119679_4964671675412083226_n.webp',
 'C:/Users/shiho/Aij/SA_Instagram/opencv/image_file\\279763435_307199478245061_6504128092339136514_n.jpg',
 'C:/Users/shiho/Aij/SA_Instagram/opencv/image_file\\279886837_158654376636686_7346496767698961590_n.webp',
 'C:/Users/shiho/Aij/SA_Instagram/opencv/image_file\\287742154_738830884032034_1749529156124350381_n.jpg',
 'C:/Users/shiho/Aij/SA_Instagram/opencv/image_file\\297177013_1131470754387191_6896203709109401460_n.jpg']

In [ ]:
onlyfiles = [f for f in listdir(image_path) if isfile(join(image_path, f))]
onlyfiles

['279693449_1091281408119679_4964671675412083226_n.webp',
 '279763435_307199478245061_6504128092339136514_n.jpg',
 '279886837_158654376636686_7346496767698961590_n.webp',
 '287742154_738830884032034_1749529156124350381_n.jpg',
 '297177013_1131470754387191_6896203709109401460_n.jpg']

**Create a pandas dataframe to append more pixel and visual features later for analysis**

In [ ]:
# Create df based on image name
def create_df_from_imagefolder(image_folder_path):
    """Create a df that has a image_name column to list all images within the specific folder"""
    onlyfiles = [f for f in listdir(image_folder_path) if isfile(join(image_folder_path, f))]
    image_df = pd.DataFrame(onlyfiles, columns=['image_name'])
    return image_df

In [ ]:
image_df = create_df_from_imagefolder("C:/Users/shiho/Aij/SA_Instagram/opencv/image_file/")
image_df

image_name
0  279693449_1091281408119679_4964671675412083226...
1  279763435_307199478245061_6504128092339136514_...
2  279886837_158654376636686_7346496767698961590_...
3  287742154_738830884032034_1749529156124350381_...
4  297177013_1131470754387191_6896203709109401460...

## Pixel Features

In [ ]:
# Colored images are default channels in B, G, R order
image_name ="287742154_738830884032034_1749529156124350381_n.jpg"
image = cv2.imread("287742154_738830884032034_1749529156124350381_n.jpg")

In [ ]:
cv2.imshow("Display window", image)
k = cv2.waitKey(0)

In [ ]:
image

array([[[ 75,  58,  55],
        [ 76,  59,  56],
        [ 77,  60,  57],
        ...,
        [ 85,  72,  96],
        [ 85,  72,  96],
        [ 84,  71,  95]],

       [[ 77,  60,  57],
        [ 78,  61,  58],
        [ 79,  62,  59],
        ...,
        [ 83,  70,  94],
        [ 84,  71,  95],
        [ 84,  71,  95]],

       [[ 80,  63,  60],
        [ 80,  63,  60],
        [ 81,  64,  61],
        ...,
        [ 81,  68,  92],
        [ 81,  68,  92],
        [ 81,  68,  92]],

       ...,

       [[126, 138, 142],
        [126, 138, 142],
        [126, 138, 142],
        ...,
        [141, 153, 157],
        [142, 154, 158],
        [141, 153, 157]],

       [[126, 138, 142],
        [126, 138, 142],
        [126, 138, 142],
        ...,
        [141, 153, 157],
        [142, 154, 158],
        [141, 153, 157]],

       [[126, 138, 142],
        [126, 138, 142],
        [126, 138, 142],
        ...,
        [141, 153, 157],
        [142, 154, 158],
        [141, 153, 157]]

In [ ]:
# Shape of image a tuple of the number of rows, columns, and channels (if the image is color)
print(image.shape)
# number of pixels
print(image.size)
# image datatype
print(image.dtype)

(935, 750, 3)
2103750
uint8


### 1. BGR Channels

In [ ]:
# BGR channels (blue, green, red)
# the split is a costly operation, use numpy indexing instead
b,g,r =cv2.split(image)
# numpy indexing
b = image[:,:,0]
g = image[:,:,1]
r = image[:,:,2]
r

array([[ 55,  56,  57, ...,  96,  96,  95],
       [ 57,  58,  59, ...,  94,  95,  95],
       [ 60,  60,  61, ...,  92,  92,  92],
       ...,
       [142, 142, 142, ..., 157, 158, 157],
       [142, 142, 142, ..., 157, 158, 157],
       [142, 142, 142, ..., 157, 158, 157]], dtype=uint8)

**BGR mean and variance**

In [ ]:
pd.DataFrame({'Blue Mean': [1], 'Red Mean': [3]})

Blue Mean  Red Mean
0          1         3

In [ ]:
def calculate_BGR_mean_variance(image = image):
    """Return the Mean and Variance of the BGR value
    Return 6 values in order: mean of blue, green, red; variance of blue, green, red
    """
    BGR_mean_variance = cv2.meanStdDev(image)
    blue_mean = float(BGR_mean_variance[0][0])
    green_mean = float(BGR_mean_variance[0][1])
    red_mean = float(BGR_mean_variance[0][2])
    blue_var = float(BGR_mean_variance[1][0]**2)
    green_var = float(BGR_mean_variance[1][1]**2)
    red_var = float(BGR_mean_variance[1][2]**2)
    return blue_mean, green_mean, red_mean, blue_var, green_var, red_var

In [ ]:
calculate_BGR_mean_variance(image)

array([129.04127201, 138.98906524, 156.45470945])

In [ ]:
calculate_BGR_mean_variance(image)

(129.04127201426024,
 138.9890652406417,
 156.45470944741533,
 1729.6729461752072,
 1720.3692522670462,
 1865.7595181063152)

**TBD: Find the dominance color of the image?**

### 2. HSV Channels

**Convert between RGB and HSV**

Reference: https://docs.opencv.org/3.4/de/d25/imgproc_color_conversions.html#color_convert_rgb_hsv

In [ ]:
# HSV channels
hsv_image = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
hsv_image

array([[[116,  68,  75],
        [116,  67,  76],
        [116,  66,  77],
        ...,
        [164,  64,  96],
        [164,  64,  96],
        [164,  64,  95]],

       [[116,  66,  77],
        [116,  65,  78],
        [116,  65,  79],
        ...,
        [164,  65,  94],
        [164,  64,  95],
        [164,  64,  95]],

       [[116,  64,  80],
        [116,  64,  80],
        [116,  63,  81],
        ...,
        [164,  67,  92],
        [164,  67,  92],
        [164,  67,  92]],

       ...,

       [[ 23,  29, 142],
        [ 23,  29, 142],
        [ 23,  29, 142],
        ...,
        [ 23,  26, 157],
        [ 23,  26, 158],
        [ 23,  26, 157]],

       [[ 23,  29, 142],
        [ 23,  29, 142],
        [ 23,  29, 142],
        ...,
        [ 23,  26, 157],
        [ 23,  26, 158],
        [ 23,  26, 157]],

       [[ 23,  29, 142],
        [ 23,  29, 142],
        [ 23,  29, 142],
        ...,
        [ 23,  26, 157],
        [ 23,  26, 158],
        [ 23,  26, 157]]

In [ ]:
# numpy indexing for HSV (Hue, Saturation, Value)
h = hsv_image[:,:,0]
s = hsv_image[:,:,1]
v = hsv_image[:,:,2]
h

array([[116, 116, 116, ..., 164, 164, 164],
       [116, 116, 116, ..., 164, 164, 164],
       [116, 116, 116, ..., 164, 164, 164],
       ...,
       [ 23,  23,  23, ...,  23,  23,  23],
       [ 23,  23,  23, ...,  23,  23,  23],
       [ 23,  23,  23, ...,  23,  23,  23]], dtype=uint8)

#### 2.1 Hue Share

#### Define the hue boundary to identify the color

According to the literature, 6 key colors (red, orange, yellow, green, blue, violet) are identified in the literature:

Kim, Y., & Kim, J. H. (2020). Using photos for public health communication: A computational analysis of the Centers for Disease Control and Prevention Instagram photos and public responses. Health Informatics Journal, 26(3), 2159-2180.

Set the range of these colors accordingly:

The above literature used the following intervals to categorize hue colors:
**May need to discuss with the team**

Use this website to test the colors: https://colorpicker.me/ (Note that the Hue range for OpenCV is [0-180], while the range for this website is [0-360])

Intervals:
- Red: 0 ~ 7, 169 ~ 180
- Orange: 7 ~ 23
- Yellow: 23 ~ 35
- Green: 35 ~ 90
- Blue: 90 ~ 136
- Violet: 136 ~ 169

In [ ]:
def get_hue_share_of_images(hue = h):
    """Get the share of six key colors (red, orange, yellow, green, blue, violet), 
    and also the share of warm (red, orange, yellow) and cold color (green, blue, violet) in a photo
    Return 8 values in order: Share of red, orange, yellow, green, blue, violet, warm, cold
    """
    hue_name_list = []
    # Flatten the hue ndarray into list
    hue_value_list = list(h.flatten())
    
    # Assign the hue name color based on values
    for i in range(0,len(hue_value_list)):
        hue_value = hue_value_list[i]
        if 7 <= hue_value < 23:
            hue_name_list.append("Orange")
        elif 23 <= hue_value < 35:
            hue_name_list.append("Yellow")
        elif 35 <= hue_value < 90:
            hue_name_list.append("Green")
        elif 90 <= hue_value < 136:
            hue_name_list.append("Blue")
        elif 136 <= hue_value <169:
            hue_name_list.append("Violet")
        else: 
            hue_name_list.append("Red")
    
    # Get the share of key colors and the warm/cold colors
    
    total_pixel = len(hue_name_list)
    pixel_color_count = Counter(hue_name_list)
    
    red_share = pixel_color_count['Red'] / total_pixel
    organge_share = pixel_color_count['Orange'] / total_pixel
    yellow_share = pixel_color_count['Yellow'] / total_pixel
    green_share = pixel_color_count['Green'] / total_pixel
    blue_share = pixel_color_count['Blue'] / total_pixel
    violet_share = pixel_color_count['Violet'] / total_pixel
    
    warm_share = red_share + organge_share + yellow_share
    cold_share = green_share + blue_share + violet_share
    
    return red_share, organge_share, yellow_share, green_share, blue_share, violet_share, warm_share, cold_share

In [ ]:
get_hue_share_of_images(h)

(0.12532192513368984,
 0.5755622103386809,
 0.11346737967914439,
 0.0581204991087344,
 0.06936042780748664,
 0.058167557932263816,
 0.814351515151515,
 0.18564848484848484)

#### 2.2 Saturation, Value and Pleasure-Arousal-Dominance model

The PAD model formula for colors is adapted from: https://d1wqtxts1xzle7.cloudfront.net/60902596/color_of_psychology20191014-57839-165md2u-with-cover-page-v2.pdf?Expires=1666589035&Signature=eJuengtAOLbO4itYuzORSrtna2snnz5oVG9P6~KDhbM9SC-gBxFNDG97gD-bc9HJ2zGJ09t6EXLyhV3JuY0nVSNVrvOlafXyjd06fXbyx~islHjJ7NMvcx4YjLGmYM1bzpRj2OBH1lccDb7EDo3uNbVbZJQdEnryJVA1vJP-CKY7j24c8nkaGlNiWfWdDXJqiTwE5Oqf18IdTvW322UgKuf-bvT0at6AnFvVoJjUqSH0htn9jLFxLHvlyNnXpd0y~UCW6tCbPzSVj84KZq7KL40Te9g4nwdbZzQtqTy2V6unUcg3vdZzH0KsOTt1hHOqwaAsx8oXASQerLsd~ogUEQ__&Key-Pair-Id=APKAJLOHF5GGSLRBV4ZA

In [ ]:
def calculate_SV_mean_variance_and_PAD(hsv_image = hsv_image):
    """Return the Mean and Variance of saturation and values, and the Pleasure, Arousal and Dominance
    Return 7 values in order: mean of saturation & value; variance of saturation & value; P & A & D 
    """
    # Saturation and Value mean/variance
    HSV_mean_variance = cv2.meanStdDev(hsv_image)
    
    saturation_mean = float(HSV_mean_variance[0][1])
    value_mean = float(HSV_mean_variance[0][2])

    saturation_var = float(HSV_mean_variance[1][1]**2)
    value_var = float(HSV_mean_variance[1][2]**2)
    
    # PAD
    pleasure = 0.69*value_mean + 0.22*saturation_mean
    arousal = -0.31*value_mean + 0.60*saturation_mean
    dominance = -0.76*value_mean + 0.32*saturation_mean
    
    return saturation_mean, value_mean, saturation_var, value_var, pleasure, arousal, dominance 

In [ ]:
calculate_SV_mean_variance_and_PAD(hsv_image)

(53.50473725490196,
 158.59976185383246,
 1516.5263782714292,
 1754.8027627240297,
 121.20487787522282,
 -17.063083821746886,
 -103.41430308734404)

In [ ]:
cv2.meanStdDev(hsv_image)[0]

array([[ 39.37221961],
       [ 53.50473725],
       [158.59976185]])

## Visual Features

### 1. Brightness

Brightness is measured using luminance in YUV color channels, the conventional ranges for Y, U, and V channel values are 0 to 255.

In [ ]:
yuv_image = cv2.cvtColor(image, cv2.COLOR_BGR2YUV)

In [ ]:
def calculate_brightness(yuv_image = yuv_image):
    """Get the brightness of a photo measured by the average of luminance
    Image type in YUV
    """
    brightness = cv2.mean(yuv_image)[0]
    return brightness

In [ ]:
calculate_brightness(yuv_image)

143.08267664884136

### 2. Colorfulness

Measures how colorful a given photo is. Reference: https://pyimagesearch.com/2017/06/05/computing-image-colorfulness-with-opencv-and-python/

The metric to evaluation the colorfulness is:

$$
rg = R - G
$$

$$
yb = \frac{1}{2}(R+G) - B
$$

where: 

$R$: Red

$G$: Green

$B$: Blue

$rg$: Difference between red channel and green channel

$yb$: Half of the sum of the red and green channels minus the blue channel

The final colorfulness metric $C$ is:

$$
\sigma_{rgyb} = \sqrt{\sigma^2_{rg} + \sigma^2_{yb}}
$$
$$
\mu_{rgyb} = \sqrt{\mu^2_{rg} + \mu^2_{yb}}
$$
$$
C = \sigma_{rgyb} + 0.3*\mu_{rgyb}
$$

where:

$\sigma$ and $\mu$ are the standard deviation and mean value of the pixel cloud along direction

In [ ]:
def calculate_colorfulness(image = image):
    """Calculate the colorfulness of an image
    Imange in BGR channel
    """
    # Split image into BGR channel
    (B, G, R) = cv2.split(image.astype('float'))
    
    # rg = R-G
    rg = np.absolute(R-G)
    
    # yb = 0.5* (R+G) - B
    yb = np.absolute(0.5*(R+G) - B)
    
    # mean and sd of 'rg' and 'yb'
    (rg_mean, rg_std) = (np.mean(rg), np.std(rg))
    (yb_mean, yb_std) = (np.mean(yb), np.std(yb))
    
    # combine mean and std
    root_mean = np.sqrt(rg_mean ** 2 + yb_mean ** 2)
    root_std = np.sqrt(rg_std **2 + yb_std ** 2)
    
    colorfulness = root_std + 0.3 * root_mean
    
    return colorfulness

In [ ]:
calculate_colorfulness(image)

39.5318242627398

### 3. Naturalness

Measures how much a given image corresponds to human perception of reality. Reference: 

https://dl.acm.org/doi/pdf/10.1145/1526709.1526813

**How to calculate naturalness:**
Reference: 
https://www.sciencedirect.com/science/article/pii/S1077314206000233?casa_token=imN184fcv10AAAAA:iQc5plIKFRVTzUFmIYludKxczXA0L0fafBAug1CCJ1hooSiP3yvmc15oq6eJieq26j6ACA3IEQ#fn4


1. Compute the luminance (L), hue (H) and saturation(S)
2. Thresholding L and S components: keep L values between 20 and 80 (in range 0 - 100), S > 0.1 (in range 0-1)
3. Define three kinds of pixels based on hue values: 25 - 70 'skin' pixels, 95 - 135 'grass' pixels, 185 - 260 'sky' pixels (in range 0-360)
4. Calculate average saturation values for skin $S_{avg\_skin}$, grass $S_{avg\_grass}$, sky $S_{avg\_sky}$ and number of skin pixels $n_{skin}$ $n_{grass}$ $n_{sky}$
5. Calculate local CNI (color naturalness index) which:
$$N_{skin} = exp(-0.5*((S_{avg\_skin} - 0.76)/0.52)^2)$$
$$N_{grass} = exp(-0.5*((S_{avg\_grass} - 0.81)/0.53)^2)$$
$$N_{sky} = exp(-0.5*((S_{avg\_sky} - 0.43)/0.22)^2)$$
6. Calculate global CNI which:
$$N_{image} = (n_{skin} * N_{skin} + n_{grass} * N_{grass} + n_{sky} * N_{sky}) / (n_{skin} +n_{grass} + n_{sky})$$

$N_{image}$ should vary from 0 (most unnatural) to 1 (most natural)

In [ ]:
def calculate_naturalness(hsv_image = hsv_image, yuv_image = yuv_image):
    """Calculate the naturalness of a image
    Require the luminance (Y) in YUV color space, Hue (H) and Saturation (S) in HSV color space
    Return a value 0 (most unnatural) - 1 (most natural) 
    """
    # Step 1:
    # Get the luminance, hue and saturation from the image
    y = yuv_image[:,:,0]
    h = hsv_image[:,:,0]
    v = hsv_image[:,:,1]
    
    # Rescale the values since the scale is different from OpenCV
    # y cv range 0-255, rescale to 0 - 100
    y_cv_range = pd.Series(y.flatten())
    y_rescaled = y_cv_range*(100/255)
    # h cv range 0-180, rescale to 0 - 360
    h_cv_range = pd.Series(h.flatten())
    h_rescaled = h_cv_range*2
    # s cv range 0-255, rescale to 0 - 1
    s_cv_range = pd.Series(s.flatten())
    s_rescaled = s_cv_range/255   
    
    #Create a pd.df to store all rescaled values
    rescaled_df = pd.DataFrame({'y_rescaled':y_rescaled, 'h_rescaled': h_rescaled, 's_rescaled' : s_rescaled})
    
    # Step 2:
    # threshold luminance and saturation components
    threshold_df = rescaled_df[(20 <= rescaled_df['y_rescaled']) & (rescaled_df['y_rescaled'] <= 80) & (rescaled_df['s_rescaled'] > 0.1)]
    threshold_df['pixel_kind'] = pd.Series()
    threshold_df = threshold_df.reset_index()
    
    # Step 3:
    # Define pixel kinds
    threshold_df = threshold_df.case_when(
            # condition, value
        (25 <= threshold_df.h_rescaled) & (threshold_df.h_rescaled <= 70), "Skin",
        (95 <= threshold_df.h_rescaled) & (threshold_df.h_rescaled <= 135), "Grass",
        (185 <= threshold_df.h_rescaled) & (threshold_df.h_rescaled <= 260), "Sky",
        np.nan,
        column_name= "pixel_kind")
    
    # Step 4:
    # calculate pixels of three pixel kinds
    pixel_count = threshold_df.pixel_kind.value_counts()
    skin_count = pixel_count['Skin']
    grass_count = pixel_count['Grass']
    sky_count = pixel_count['Sky']

    # calculate the averaged saturation values for three pixel kinds
    skin_s = threshold_df.loc[threshold_df['pixel_kind'] == 'Skin', 's_rescaled'].mean()
    grass_s = threshold_df.loc[threshold_df['pixel_kind'] == 'Grass', 's_rescaled'].mean()
    sky_s = threshold_df.loc[threshold_df['pixel_kind'] == 'Sky', 's_rescaled'].mean()
    
    # Step 5: 
    # Calculate local CNI values for three pixel kinds
    N_skin = math.exp(-0.5*((skin_s - 0.76)/0.52)**2)
    N_grass = math.exp(-0.5*((grass_s - 0.81)/0.53)**2)
    N_sky = math.exp(-0.5*((sky_s - 0.43)/0.22)**2)
    
    # Step 6:
    # Calculate the global CNI values
    N_image = (skin_count*N_skin + grass_count * N_grass + sky_count * N_sky)/(skin_count + grass_count + sky_count)
    
    return N_image

In [ ]:
calculate_naturalness(hsv_image = hsv_image, yuv_image= yuv_image)

0.6214029704309361

In [ ]:
# Create a pd dataframe that stores all the rescaled values
#pd.Series()
# y cv range 0-255, rescale to 0 - 100
y_cv_range = pd.Series(y.flatten())
y_rescaled = y_cv_range*(100/255)
# h cv range 0-180, rescale to 0 - 360
h_cv_range = pd.Series(h.flatten())
h_rescaled = h_cv_range*2
# s cv range 0-255, rescale to 0 - 1
s_cv_range = pd.Series(s.flatten())
s_rescaled = s_cv_range/255

In [ ]:
rescaled_df = pd.DataFrame({'y_rescaled':y_rescaled, 'h_rescaled': h_rescaled, 's_rescaled' : s_rescaled})

In [ ]:
# threshold luminance and saturation components
threshold_df = rescaled_df[(20 <= rescaled_df['y_rescaled']) & (rescaled_df['y_rescaled'] <= 80) & (rescaled_df['s_rescaled'] > 0.1)]
threshold_df['pixel_kind'] = pd.Series()
threshold_df = threshold_df.reset_index()

In [ ]:
threshold_df = threshold_df.case_when(
    # condition, value
    (25 <= threshold_df.h_rescaled) & (threshold_df.h_rescaled <= 70), "Skin",
    (95 <= threshold_df.h_rescaled) & (threshold_df.h_rescaled <= 135), "Grass",
    (185 <= threshold_df.h_rescaled) & (threshold_df.h_rescaled <= 260), "Sky",
    np.nan,
    column_name= "pixel_kind")
threshold_df

index  y_rescaled  h_rescaled  s_rescaled pixel_kind
0            0   23.137255         232    0.266667        Sky
1            1   23.529412         232    0.262745        Sky
2            2   23.921569         232    0.258824        Sky
3            3   24.313725         232    0.254902        Sky
4            4   24.313725         232    0.254902        Sky
...        ...         ...         ...         ...        ...
507377  701245   59.607843          46    0.101961       Skin
507378  701246   60.000000          46    0.101961       Skin
507379  701247   60.000000          46    0.101961       Skin
507380  701248   60.392157          46    0.101961       Skin
507381  701249   60.000000          46    0.101961       Skin

[507382 rows x 5 columns]

In [ ]:
# calculate pixels of three pixel kinds
pixel_count = threshold_df.pixel_kind.value_counts()
skin_count = pixel_count['Skin']
grass_count = pixel_count['Grass']
sky_count = pixel_count['Sky']

# calculate the averaged saturation values for three pixel kinds
skin_s = threshold_df.loc[threshold_df['pixel_kind'] == 'Skin', 's_rescaled'].mean()
grass_s = threshold_df.loc[threshold_df['pixel_kind'] == 'Grass', 's_rescaled'].mean()
sky_s = threshold_df.loc[threshold_df['pixel_kind'] == 'Sky', 's_rescaled'].mean()

print(skin_count, grass_count, sky_count, skin_s, grass_s, sky_s)

290916 7307 25025 0.22718566561502157 0.3292142640551125 0.36397155785382557


In [ ]:
# Calculate local CNI values for three pixel kinds
N_skin = math.exp(-0.5*((skin_s - 0.76)/0.52)**2)
N_grass = math.exp(-0.5*((grass_s - 0.81)/0.53)**2)
N_sky = math.exp(-0.5*((sky_s - 0.43)/0.22)**2)
print(N_skin, N_grass, N_sky)

# Calculate the global CNI values
N_image = (skin_count*N_skin + grass_count * N_grass + sky_count * N_sky)/(skin_count + grass_count + sky_count)
print(N_image)

0.5915869612173066 0.6626859251858856 0.9559603964448348
0.6214029704309361


### 4. Contrast

Measures the relative variation of luminance. Reference: 
https://dl.acm.org/doi/pdf/10.1145/1526709.1526813

**How to calculate RMS contrast**
$$C^{RMS} = \frac{1}{n-1}*\sum_{i=1}^{n}(x_{i} - \bar{x})^2 $$

where:

$x$ is the luminance

In [ ]:
def calculate_rms_contrast(yuv_image = yuv_image):
    """Calculate the contrast of an image
    Require the luminance (Y) in YUV color space
    """
    # Luminance mean / std
    YUV_mean_std = cv2.meanStdDev(yuv_image)

    contrast = float(YUV_mean_std[1][0])
    return contrast

In [ ]:
calculate_rms_contrast(yuv_image)

39.95643430846404

### 5. RGB Contrast

No reference, TBD

### 6. Sharpness

### Update: Use the package that calculates the sharpness instead, its in the image_quality_explore script folder

Measures the clarity and level of detail of an image. Reference: https://dl.acm.org/doi/pdf/10.1145/1526709.1526813

https://dsp.stackexchange.com/questions/54687/python-how-to-compute-the-sharpness-features-of-image

**How to calculate sharpness**

Sharpness can be determined as a function of its Laplacian, normalized by the local average luminance in the surroundings of each pixel:

$$\text{Sharpness} = \sum_{x,y} \frac{L(x,y)}{\mu_{xy}}$$ 

with $L(x,y) = \displaystyle \frac{\partial^{2} I}{\partial x^2} + \frac{\partial^{2} I}{\partial y^2} $, where $\mu_{xy}$ denotes the local average luminance around pixel (x,y) 

The Laplacian is calculated through Laplacian function in OpenCV, the local average luminance is calculated through blurring. The nature of blurring is to average a neighborhood of pixels within a given radius, get the local average luminance from the blurred image

In [ ]:
# def calculate_sharpness(image = image, yuv_image = yuv_image):
#     """Calculate the sharpness of the image
#     Require the BGR image, and the luminance (Y) in YUV color space
#     """
#     # Calculate the Laplacian of the luminance, use pixels in 3 X 3 spaces to calculate local average
#     y = yuv_image[:,:,0]
#     lap_y = cv2.Laplacian(y, cv2.CV_16S, ksize = 3)
    
#     # Calculate the local average of the luminance by utilizing blurring
#     # Get the blurred BGR image, use pixels in 3 x 3 spaces to calculate local average
#     local_mean_blur = cv2.GaussianBlur(image,(3,3),cv2.BORDER_DEFAULT)
    
#     # Convert to YUV image to get the local average luminance
#     avg_yuv = cv2.cvtColor(local_mean_blur, cv2.COLOR_BGR2YUV)
#     avg_y = avg_yuv[:,:,0]
    
#     # Calculate the Sharpness through pd.Series operation
#     lap_y_series = pd.Series(lap_y.flatten())
#     avg_y_series = pd.Series(avg_y.flatten()).apply(int)
#     sharpness = sum(lap_y_series/avg_y_series)
    
#     return sharpness

In [ ]:
calculate_sharpness(image, yuv_image)

5690.682954811724

In [ ]:
lap_y_series = pd.Series(lap_y.flatten())
lap_y_series

0         24
1         16
2         12
3          8
4          8
          ..
701245     0
701246    -4
701247     4
701248    -8
701249     8
Length: 701250, dtype: int16

In [ ]:
avg_y_series = pd.Series(avg_y.flatten()).apply(int)
avg_y_series

0          61
1          61
2          62
3          63
4          63
         ... 
701245    152
701246    153
701247    153
701248    153
701249    154
Length: 701250, dtype: int64

In [ ]:
sum(lap_y_series/avg_y_series)

5690.682954811724

In [ ]:
# The nature of blurring is to average a neighborhood of pixels within a given radius
# Get the blurred BGR image
local_mean_blur = cv2.GaussianBlur(image,(3,3),cv2.BORDER_DEFAULT)
# Convert to YUV image to get the local average luminance
avg_yuv = cv2.cvtColor(local_mean_blur, cv2.COLOR_BGR2YUV)
avg_y = avg_yuv[:,:,0]

In [ ]:
avg_y

array([[ 61,  61,  62, ...,  80,  80,  80],
       [ 62,  62,  63, ...,  79,  79,  79],
       [ 64,  64,  64, ...,  77,  77,  77],
       ...,
       [138, 138, 138, ..., 153, 153, 154],
       [138, 138, 138, ..., 153, 153, 154],
       [138, 138, 138, ..., 153, 153, 154]], dtype=uint8)

In [ ]:
cv2.imshow("Display window", lap_1_abs)
k = cv2.waitKey(0)

In [ ]:
cv2.imshow("Display window", cv2.GaussianBlur(image,(3,3),cv2.BORDER_DEFAULT))
k = cv2.waitKey(0)

### 7. Color Diversity

### 8. Color Harmony

In [ ]:
# This code set all red pixels to zero
# image[:,:,2] = 0
# image = cv2.merge((b,g,r))

In [ ]:
cv2.cvtColor(np.uint8([[[255,0,0 ]]]),cv2.COLOR_BGR2HSV)

array([[[120, 255, 255]]], dtype=uint8)

In [ ]:
cv2.line(image, (0,0), (100,100), (255,0,0), 5)
cv2.imshow("Display window", image)
k = cv2.waitKey(0)

In [ ]:
# import the library opencv
import cv2
# globbing utility.
import glob
# select the path
path = "C:/Users/shiho/Aij/SA_Instagram/opencv/image_file/*.*"
for file in glob.glob(path):
    image_read = cv2.imread(file)
    # conversion numpy array into rgb image to show
    c = cv2.cvtColor(image_read, cv2.COLOR_BGR2RGB)
    cv2.imshow('Color image', c)
    # wait for 1 second
    k = cv2.waitKey(1000)
    # destroy the window
    cv2.destroyAllWindows()

In [ ]:
from os import listdir
from os.path import isfile, join
import numpy
import cv2

mypath='C:/Users/shiho/Aij/SA_Instagram/opencv/image_file'
onlyfiles = [ f for f in listdir(mypath) if isfile(join(mypath,f)) ]
images = numpy.empty(len(onlyfiles), dtype=object)
for n in range(0, len(onlyfiles)):
    images[n] = cv2.imread( join(mypath,onlyfiles[n]) )

In [ ]:
mylist = []
loaded,mylist = cv2.imreadmulti(mats = mylist, filename = "C:/Users/shiho/Aij/SA_Instagram/opencv/image_file/*.*", flags = cv2.IMREAD_ANYCOLOR )

# alternative usage 
#loaded,mylist = cv2.imreadmulti(mats = mylist, start =0, count = 2, filename = "2page.tiff", flags = cv2.IMREAD_ANYCOLOR )

#cv2.imshow("mylist[0]",mylist[0])
#cv2.imshow("mylist[1]",mylist[1])
#cv2.waitKey()

In [ ]:
loaded

False

In [ ]:
ti_data = pd.read_csv("collecting_test.csv", encoding= "UTF-8")

In [ ]:
ti_data.head(20)

user_id             status_id           created_at  \
0           x2794120980  x1584978238082023424  2022-10-25 18:40:34   
1           x2794120980  x1584906333236899841  2022-10-25 13:54:50   
2           x2794120980  x1584579213063229440  2022-10-24 16:14:59   
3           x2794120980  x1584537158609956864  2022-10-24 13:27:52   
4   x703873696113373184  x1584976386070310912  2022-10-25 18:33:12   
5           x2340148272  x1584975267075801089  2022-10-25 18:28:45   
6   x781083964148768769  x1584970014888599552  2022-10-25 18:07:53   
7   x781083964148768769  x1584551552949575680  2022-10-24 14:25:04   
8   x781083964148768769  x1584592337233055744  2022-10-24 17:07:08   
9             x56177032  x1584968094652723200  2022-10-25 18:00:15   
10          x1227015854  x1584960967431036928  2022-10-25 17:31:56   
11          x1227015854  x1584892682412883969  2022-10-25 13:00:36   
12            x25503818  x1584953711243440128  2022-10-25 17:03:06   
13            x25503818  x1584829016611045376  2022-10-25 08:47:36   
14           x113029646  x1584951131801006081  2022-10-25 16:52:51   
15           x309477766  x1584949570483937281  2022-10-25 16:46:39   
16  x900664101986328580  x1584592555815075849  2022-10-24 17:08:00   
17  x900664101986328580  x1584568393574719488  2022-10-24 15:31:59   
18  x900664101986328580  x1584532709401317376  2022-10-24 13:10:11   
19  x900664101986328580  x1584884227816013824  2022-10-25 12:27:00   

      screen_name                                               text  \
0     duelissorry  For sale: Last 1 tickets of Dota 2 The Interna...   
1     duelissorry  Still have 1 ticket, Buyer wanted a refund. \r...   
2     duelissorry  last 1 finals ticket for 540 sgd each pls dm m...   
3     duelissorry  last 2 finals ticket for 580 sgd each pls dm m...   
4   DarcyMargallo  Another worlds, another year to clown on Riot ...   
5    MalystryxGDS  My journey begins to Singapore for #TI11 !! UK...   
6        ggbet_en  He approached AWF at a LAN cafe and asked if h...   
7        ggbet_en  Let's take a look at some #TI11 main event sta...   
8        ggbet_en  While waiting for #TI11 finals, let's do a lit...   
9     jankenqueen  boyfriend just called me to ask "DID YOU WATCH...   
10    Dota2Lounge  This will be the venue for the last 2 days of ...   
11    Dota2Lounge  Look at this amazing phoenix set for the colle...   
12     syasyapuff  Hi friends! Does anyone know if there has been...   
13     syasyapuff  Can’t wait to attend my 3rd @dota2 TI with @se...   
14   VipPlaymaker  VIP OPEN WEEKLY QUESTS 1 - 8 BONUS WEEK https:...   
15    chenwilliam  For sale: Last 2 tickets of Dota 2 The Interna...   
16  1xBet_Esports  Let them FINNISH <U+0001F1EB><U+0001F1EE> #TI1...   
17  1xBet_Esports  Only two players are still eligible for a two-...   
18  1xBet_Esports  His world tour concert was the reason of such ...   
19  1xBet_Esports  Play-off statistics #TI11 <U+0001F4CA>\r\n\r\n...   

                 source  display_text_width reply_to_status_id  \
0       Twitter Web App                 175                NaN   
1       Twitter Web App                 145                NaN   
2       Twitter Web App                 122                NaN   
3       Twitter Web App                 122                NaN   
4   Twitter for Android                 191                NaN   
5   Twitter for Android                 222                NaN   
6       Twitter Web App                 225                NaN   
7       Twitter Web App                 122                NaN   
8       Twitter Web App                 267                NaN   
9       Twitter Web App                 124                NaN   
10            TweetDeck                  58                NaN   
11            TweetDeck                  82                NaN   
12   Twitter for iPhone                  75                NaN   
13   Twitter for iPhone                 173                NaN   
14      Twitter Web App                 15